// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    advisors: {
        name: "advisors";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          advisor_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          title: string;
          /** @sqlType STRING */
          initials: string;
        }>;
      };
    asset_allocation: {
        name: "asset_allocation";
        parameters: {
          /** any - use sql.*() */
          advisor_id: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          asset_class: string;
          /** @sqlType DOUBLE */
          pct_of_portfolio: number;
        }>;
      };
    concentration_risk: {
        name: "concentration_risk";
        parameters: {
          /** any - use sql.*() */
          advisor_id: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          asset_class: string;
          /** @sqlType STRING */
          client_name: string;
          /** @sqlType DOUBLE */
          delta_pct: number;
        }>;
      };
    document_insights: {
        name: "document_insights";
        parameters: {
          /** any - use sql.*() */
          holding_id: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          kpi_name: string;
          /** @sqlType STRING */
          prior_value: string;
          /** @sqlType STRING */
          current_value: string;
          /** @sqlType DECIMAL(3,1) */
          change_pct: number;
          /** @sqlType STRING */
          flag: string;
          /** @sqlType DECIMAL(1,1) */
          covenant_value: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** any - use sql.*() */
          message: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    holdings_list: {
        name: "holdings_list";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          holding_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          asset_class: string;
          /** @sqlType STRING */
          strategy: string;
          /** @sqlType BOOLEAN */
          has_alert: boolean;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** any - use sql.*() */
          max_month_num: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
    performance_timeseries: {
        name: "performance_timeseries";
        parameters: {
          /** any - use sql.*() */
          advisor_id: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          date: string;
          /** @sqlType DOUBLE */
          portfolio_return: number;
          /** @sqlType DOUBLE */
          benchmark_return: number;
        }>;
      };
    portfolio_summary: {
        name: "portfolio_summary";
        parameters: {
          /** any - use sql.*() */
          advisor_id: SQLTypeMarker;
        };
        result: unknown;
      };
    top_holdings: {
        name: "top_holdings";
        parameters: {
          /** any - use sql.*() */
          advisor_id: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          holding_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          asset_class: string;
          /** @sqlType DOUBLE */
          aum_millions: number;
          /** @sqlType DOUBLE */
          pct_of_portfolio: number;
          /** @sqlType DOUBLE */
          ytd_return: number;
          /** @sqlType STRING */
          risk_flag: string;
        }>;
      };
  }
}
