// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    asset_allocation: {
        name: "asset_allocation";
        parameters: Record<string, never>;
        result: unknown;
      };
    concentration_risk: {
        name: "concentration_risk";
        parameters: Record<string, never>;
        result: unknown;
      };
    document_insights: {
        name: "document_insights";
        parameters: {
          /** any - use sql.*() */
          holding_id: SQLTypeMarker;
        };
        result: unknown;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** any - use sql.*() */
          message: SQLTypeMarker;
        };
        result: unknown;
      };
    holdings_list: {
        name: "holdings_list";
        parameters: Record<string, never>;
        result: unknown;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** any - use sql.*() */
          max_month_num: SQLTypeMarker;
        };
        result: unknown;
      };
    performance_timeseries: {
        name: "performance_timeseries";
        parameters: Record<string, never>;
        result: unknown;
      };
    portfolio_summary: {
        name: "portfolio_summary";
        parameters: Record<string, never>;
        result: unknown;
      };
    top_holdings: {
        name: "top_holdings";
        parameters: Record<string, never>;
        result: unknown;
      };
  }
}
