import { renderMarkdown } from '../../lib/markdown';
import type { Conversation } from './types';

const ADVISOR_NAME = 'James Chen';
const ADVISOR_TITLE = 'Managing Director, Private Wealth';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatTimestamp(ms: number): string {
  return new Date(ms).toLocaleString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

function buildTranscript(conv: Conversation): string {
  return conv.messages
    .filter((m) => m.content.trim().length > 0)
    .map((m) => {
      if (m.role === 'user') {
        return `<div class="msg user">
  <div class="msg-label">Advisor</div>
  <div class="msg-body user-body">${escapeHtml(m.content)}</div>
</div>`;
      }
      return `<div class="msg assistant">
  <div class="msg-label">Meridian Advisor Intelligence</div>
  <div class="msg-body">${renderMarkdown(m.content)}</div>
</div>`;
    })
    .join('\n');
}

function buildHtml(conv: Conversation): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(conv.title)} — Meridian Advisor Intelligence</title>
<style>
  @page {
    size: letter;
    margin: 0.7in 0.7in 0.9in 0.7in;
    @bottom-left {
      content: "Internal use only · Generated by Meridian Advisor Intelligence";
      font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
      font-size: 8pt;
      color: #666;
    }
    @bottom-right {
      content: "Page " counter(page) " of " counter(pages);
      font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
      font-size: 8pt;
      color: #666;
    }
  }
  * { box-sizing: border-box; }
  html, body {
    font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    color: #1a1a1a;
    font-size: 10.5pt;
    line-height: 1.5;
    margin: 0;
    padding: 0;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .header { border-bottom: 1px solid #c8a96a; padding-bottom: 14px; margin-bottom: 22px; }
  .wordmark-text {
    font-size: 16pt;
    font-weight: 700;
    letter-spacing: 0.1em;
    color: #0E1928;
  }
  .subwordmark { color: #555; font-size: 9pt; margin: 8px 0 0; letter-spacing: 0.06em; text-transform: uppercase; }
  .conv-title { font-size: 14pt; font-weight: 600; color: #0E1928; margin: 18px 0 4px; }
  .conv-meta { color: #666; font-size: 9pt; margin-bottom: 10px; }

  .msg { margin: 14px 0; }
  .msg-label {
    text-transform: uppercase;
    font-size: 8pt;
    font-weight: 700;
    letter-spacing: 0.06em;
    color: #0E1928;
    margin-bottom: 4px;
    page-break-after: avoid;
    break-after: avoid;
  }
  .msg.user .msg-label { color: #555; }
  .msg-body { font-size: 10.5pt; }
  .user-body {
    background: #f4f6f8;
    border-left: 3px solid #0E1928;
    padding: 8px 12px;
    white-space: pre-wrap;
  }

  /* Markdown render styles (target bare elements; tailwind classes are ignored here) */
  .msg-body h2 { font-size: 14pt; font-weight: 700; color: #0E1928; margin: 16px 0 6px; page-break-after: avoid; break-after: avoid; }
  .msg-body h3 { font-size: 12.5pt; font-weight: 700; color: #0E1928; margin: 14px 0 6px; page-break-after: avoid; break-after: avoid; }
  .msg-body h4 { font-size: 11.5pt; font-weight: 700; color: #0E1928; margin: 12px 0 5px; page-break-after: avoid; break-after: avoid; }
  .msg-body p { margin: 4px 0; }
  .msg-body ul { margin: 6px 0; padding-left: 20px; }
  .msg-body li { margin: 2px 0; }
  .msg-body strong { color: #0E1928; }
  .msg-body code {
    background: #f4f6f8;
    padding: 1px 4px;
    border-radius: 3px;
    font-family: ui-monospace, "SF Mono", Menlo, monospace;
    font-size: 9.5pt;
  }
  .msg-body hr { border: 0; border-top: 1px solid #e5e5e5; margin: 12px 0; }
  .msg-body blockquote {
    border-left: 2px solid #0E1928;
    padding-left: 10px;
    color: #555;
    margin: 8px 0;
    font-style: italic;
  }
  .msg-body table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 9.5pt; }
  /* Tables: allow splitting across pages but keep rows intact, repeat header on continuation. */
  .msg-body table { page-break-inside: auto; }
  .msg-body thead { display: table-header-group; }
  .msg-body tr { page-break-inside: avoid; break-inside: avoid; }
  .msg-body th {
    background: #f4f6f8;
    color: #0E1928;
    text-align: left;
    padding: 6px 8px;
    border: 1px solid #d8dde3;
    font-weight: 600;
  }
  .msg-body td { padding: 5px 8px; border: 1px solid #e5e7eb; }
  .msg-body td[class*="text-right"] { text-align: right; }
  .msg-body td[class*="tabular-nums"] { font-variant-numeric: tabular-nums; }
</style>
</head>
<body>
  <div class="header">
    <div class="wordmark-text">MERIDIAN <span style="font-weight:400;letter-spacing:0.12em;color:#555;font-size:13pt">Wealth Partners</span></div>
    <p class="subwordmark">Private Wealth Management · Advisor Intelligence</p>
  </div>
  <div class="conv-title">${escapeHtml(conv.title)}</div>
  <div class="conv-meta">${escapeHtml(ADVISOR_NAME)} · ${escapeHtml(ADVISOR_TITLE)} · Exported ${formatTimestamp(Date.now())}</div>
  <div class="transcript">
    ${buildTranscript(conv)}
  </div>
</body>
</html>`;
}

export function exportChatPdf(conv: Conversation) {
  if (typeof window === 'undefined') return;
  if (conv.messages.length === 0) {
    window.alert('Cannot export an empty conversation.');
    return;
  }
  const html = buildHtml(conv);
  const w = window.open('', '_blank');
  if (!w) {
    window.alert('Pop-up blocked. Please allow pop-ups for this site to export PDFs.');
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();

  const triggerPrint = () => {
    w.focus();
    w.print();
  };
  const img = w.document.querySelector('img.wordmark-img') as HTMLImageElement | null;
  if (img && !img.complete) {
    img.addEventListener('load', triggerPrint, { once: true });
    img.addEventListener('error', triggerPrint, { once: true });
    // Safety timeout in case the image never resolves.
    setTimeout(triggerPrint, 1500);
  } else {
    setTimeout(triggerPrint, 200);
  }
}
